### ISSUE TITLE
バグ報告

### ISSUE THREAD

**Issue by FoolZirafu** [YamikarasuMk22/HeartBeatSimulatorIssueForm#1]
・聴診器中にセリフが出ると、スタートメニュー（話す、診察などが表示された状態）になります
具体的には、負荷をかけた状態で不整脈が起きた時の「やば、心臓が～」のセリフが出た時です
聴診器は使えるけど「やめる」のスイッチが「プレイ」の上にかぶって表示されてます、やめるを押すと聴診器モードを終了し元に戻りはします

・「心音を常に再生」をオフにした状態で直聞きをしても心音が流れないのは仕様でしょうか？

注射器を選択するたびに「興奮剤」の数値が０％になってます

少々雑な報告になってしまい、申し訳ありません
ゆっくりと制作頑張ってください、応援しております！

**Comment by YamikarasuMk22** [comment]
報告ありがとうございます！確認します。

**Comment by YamikarasuMk22** [comment]
v0.0.2 にてバグの修正を行いました。
ご報告ありがとうございました。
https://fantia.jp/posts/2768268
