### ISSUE TITLE
胸の拍動の表示が不自然

### ISSUE THREAD

**Issue by sionne45** [YamikarasuMk22/HeartBeatSimulatorIssueForm#2]
心拍数が200と210の間の胸の拍動の切り替わりが不自然

209までは力強く拍動しているのに
210からいきなり弱弱しい拍動になる

**Comment by YamikarasuMk22** [comment]
報告ありがとうございます！確認します。

**Comment by YamikarasuMk22** [comment]
v0.0.2 にてバグの修正を行いました。
ご報告ありがとうございました。
https://fantia.jp/posts/2768268
