### ISSUE TITLE
Heartrate goes to negative (v0.03 Demo)

### ISSUE THREAD

**Issue by gitsslem** [YamikarasuMk22/HeartBeatSimulatorIssueForm#3]
**Describe the bug**

-The heartrate and RR goes to negative when clicking "force Af1" during breath holding at the start of the game. 

**To Reproduce**
バグが発生するまでの手順を書いてください。

1. Go to 'Play'
2. Click on 'Breath hold then start breath hold'
3. Open Debug 'Click Force Af1'
4. The character responds then the Heart rate and RR is in the negatives.

**Expected behavior**
どのように修正されるべきかをここに書いてください。

- The character breath holds and when "Force Af1" happened it reacted to the "Force Af1" then reacted the second time without even clicking the "Force Af1" then the charecters heart rate & RR is in the negatives.

**Screenshots**
If applicable, add screenshots to help explain your problem. [Optional]
スクリーンショットがある場合ここに添付してください。[任意]

**Desktop (please complete the following information):** [Optional]
バグが発生したデバイスの情報をここに書いてください (PC用)。[任意]

**Smartphone (please complete the following information):** [Optional]
バグが発生したデバイスの情報をここに書いてください (スマホ用)。[任意]

**Additional context**
Add any other context about the problem here. [Optional]
その他、何かあればここに書いてください。[任意]

-Unable replicate the error about the third time and forgot to screenshot it..
-It fix it self when clicking "Force Af1"

**Comment by YamikarasuMk22** [comment]
Thank you report!

**Comment by YamikarasuMk22** [comment]
This bug has been fixed, please wait for the v0.0.4 Demo release.

**Comment by gitsslem** [comment]
> Thank you report!

your welcome!
